# -*- coding: utf-8 -*-
"""predict.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11zY5W7ygmD73Qh7EbJvabFRg0LSnP7Zv
"""

import pandas as pd
import torch
from torch.utils.data import Dataset, DataLoader
from transformers import AutoTokenizer, AutoModelForSequenceClassification

class DNADataset(Dataset):
    def __init__(self, sequences, labels, tokenizer, max_length=512):
        self.sequences = [seq.split() for seq in sequences] 
        self.labels = labels
        self.tokenizer = tokenizer
        self.max_length = max_length

    def __len__(self):
        return len(self.sequences)

    def __getitem__(self, idx):
        seq = self.sequences[idx]
        label = self.labels[idx]
        encoding = self.tokenizer(
            seq,
            is_split_into_words=True,
            padding='max_length',
            truncation=True,
            max_length=self.max_length,
            return_tensors='pt'
        )
        item = {key: val.squeeze(0) for key, val in encoding.items()}
        item['labels'] = torch.tensor(label, dtype=torch.long)
        return item

tokenizer = AutoTokenizer.from_pretrained("zhihan1996/DNA_bert_6", trust_remote_code=True)

model_path = "/content/drive/MyDrive/DNA_BERT_models/len500/dna_bert_epoch3.pth"
model = AutoModelForSequenceClassification.from_pretrained(
    "zhihan1996/DNA_bert_6",
    trust_remote_code=True,
    num_labels=2
)

state_dict = torch.load(model_path, map_location="cpu")  # 如果 GPU 可用也可以 map_location=device
model.load_state_dict(state_dict)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)
model.eval()

df = pd.read_csv("/content/drive/MyDrive/len500/dev.csv")
sequences = df['sequence'].tolist()
labels = df['label'].tolist()

dev_dataset = DNADataset(sequences, labels, tokenizer, max_length=512)
dev_loader = DataLoader(dev_dataset, batch_size=32, shuffle=False)

all_preds = []
all_labels = []
y_score = []

with torch.no_grad():
    for batch in dev_loader:
        input_ids = batch['input_ids'].to(device)
        attention_mask = batch['attention_mask'].to(device)
        labels = batch['labels'].to(device)

        outputs = model(input_ids=input_ids, attention_mask=attention_mask)
        logits = outputs.logits
        preds = torch.argmax(logits, dim=-1)
        probs = torch.softmax(logits, dim=-1)[:, 1]

        all_preds.append(preds.cpu())
        all_labels.append(labels.cpu())
        y_score.append(probs.cpu())

all_preds = torch.cat(all_preds)
all_labels = torch.cat(all_labels)
y_score = torch.cat(y_score)

accuracy = (all_preds == all_labels).float().mean()
print("Dev Accuracy:", accuracy.item())

import numpy as np
np.savez("/content/drive/MyDrive/rice_project/eval_results_ENC003left.npz", all_preds=all_preds, all_labels=all_labels, y_score=y_score)



